### ISSUE TITLE
Only available on macOS 11?

### ISSUE THREAD

**Issue by apizz** [ninxsoft/LowProfile#1]
I would think this app would immensely more useful and accessible if it was supported on at least 10.14 or 10.15 ....

**Comment by ninxsoft** [comment]
I agree, the app would definitely be more useful if it supported older operating systems.

Some app architecture decisions were made. The UI is written in SwiftUI (only available on **macOS 10.15+**) and the app lifecycle code is written in SwiftUI (only available on **macOS 11.0+**). Hence why it is only available on **Big Sur** and later.

The cost of dealing with [OSS](https://en.wikipedia.org/wiki/Open-source_software) perhaps? 🙃
