### ISSUE TITLE
Command Line support for exporting LowProfile reports

### ISSUE THREAD

**Issue by BigMacAdmin** [ninxsoft/LowProfile#18]
### :bulb: Description

Describe clearly and concisely the feature you would like to see implemented. Is your feature request related to an active bug report?

Feature Request. LowProfile 4.0 supports an export feature which can be sent and viewed on other computers. Awesome! Is it possible to get this scriptable?

Example: `/Applications/LowProfile.app/Contents/MacOS/LowProfile --export --output /Users/Shared/export.lowprofile`

### :white_check_mark: Proposed solution

Describe what you would like to see happen.

I would like to be able to deploy LowProfile into an unknown environment, perhaps prior to an MDM migration, and export reports from several computers so that they can be analyzed by technicians.

### :adhesive_bandage: Alternatives Solutions + Workarounds

Describe any alternative solutions or approaches you have considered or implemented to workaround the missing feature.

Currently end users would need to be asked to open the app, create the report, and email it (or this could be done on a remote session).

### :information_source: Additional context

- Links to 3rd-party tools / references / documentation
- Screenshots / diagrams that help explain the feature request

**Comment by ninxsoft** [comment]
Here we go - #23:

```shell
"/Applications/Low Profile.app/Contents/MacOS/Low Profile" --export ~/Desktop/Test.lowprofile

Exported Low Profile report: '/Users/ninxsoft/Desktop/Test.lowprofile'
```

:warning: As **Low Profile.app** is a GUI / non-CLI app, the user interface will launch / flash briefly as the report is being exported.
