### ISSUE TITLE
Feature Request - Ability to inspect currently-installed Profiles

### ISSUE THREAD

**Issue by hkystar35** [ninxsoft/LowProfile#3]
I'm nowhere near smart enough to figure it out, but being able to inspect the Profiles already installed on a device would be awesome for validating payloads and signature, as well as provide a better view that the Profiles pane (which isn't resize-able).

**Comment by ninxsoft** [comment]
A short term solution may be to view the contents of payloads via **System Information.app** > **Software** > **Profiles**

However I agree, would be cool if there was a better / more intuitive way of viewing enforced configuration profiles.

Will look into this!
