### ISSUE TITLE
Allow exporting a report which we can open on another device

### ISSUE THREAD

**Issue by BigMacAdmin** [ninxsoft/LowProfile#6]
Similar to how System Information works, I would like to be able to export a "report" of all the data shown by Low Profile and then open that report on another computer to view it.

I recognize this is a huge request, so just an idea if you wanted to add more functionality.

I will soon have the need to migrate an environment from one MDM server to another, without the luxury of having access to the original server. Being able to do some exports for later review would be very helpful.

Extra super bonus points if we can script it.

**Comment by ninxsoft** [comment]
@BigMacAdmin apologies for the delay, I am finally getting around to this 🙏

Is this still something you require? Individual `.mobileconfig` files can just be copied across and opened on another computer - am I right in understanding your request relates to exporting a report of installed configuration profiles?

Would running the following command solve your problem? This is actually what Low Profile is doing under the hood:

```bash
system_profiler SPConfigurationProfileDataType -detailLevel full -xml
```

Not completely opposed to the suggestion, just trying to work out the use case + demand 🙂👍

**Comment by ninxsoft** [comment]
The Low Profile report can be exported via the toolbar menu:

![Export](https://github.com/ninxsoft/LowProfile/assets/4812595/396a1927-99f8-4bd7-8886-5b86a82698d2)

The file extension is `.lowprofile`, and the file icon looks like this:

![File Icon](https://github.com/ninxsoft/LowProfile/assets/4812595/8e81b788-78ff-43cb-a8a3-2585f47abd61)

These reports can be opened, just like `.mobileconfig` files:

![Report](https://github.com/ninxsoft/LowProfile/assets/4812595/03bca582-c92b-4c87-99a5-bd35c60f755f)
