### ISSUE TITLE
Add function to search for duplicate/overlapping keys between profiles

### ISSUE THREAD

**Issue by kevinmcox** [ninxsoft/LowProfile#7]
As discussed on the MacAdmins Slack, it would be cool if LowProfile had a feature to check all installed profiles for any overlapping/conflicting/duplicate keys.

https://macadmins.slack.com/archives/C03K5RQ6H7S/p1671119556514509

**Comment by ninxsoft** [comment]
Progress...

![Issues](https://github.com/ninxsoft/LowProfile/assets/4812595/8156de36-afa7-449c-8164-9e7d138c5ae9)

**Comment by ninxsoft** [comment]
Finally!

**Duplicated Profile Keys (Multiple Profiles):**
![Screenshot 2023-08-27 at 4 36 11 pm](https://github.com/ninxsoft/LowProfile/assets/4812595/cb8f0fea-f47d-40b2-893b-be79aa7e987e)

**Deprecated Profile Keys (Multiple Profiles):**
![Screenshot 2023-08-27 at 4 36 14 pm](https://github.com/ninxsoft/LowProfile/assets/4812595/5548a72e-4b62-4380-b03b-d61dbf6abcbe)

**Duplicated Profile Keys (Single Profile):**
![Screenshot 2023-08-27 at 4 36 29 pm](https://github.com/ninxsoft/LowProfile/assets/4812595/61dbaf74-c746-4095-9fe9-ea0d873e4865)
